import React, { useRef, useState } from 'react';
import { Upload, FileText, CheckCircle, Search, ArrowRight, ArrowLeft, Loader2, X, AlertCircle, Edit, BookOpen, Clock } from 'lucide-react';
import { FiscalDocument, InvoiceItem, DocumentsProps, AILearning, AuditEntry } from '../types';
import { documentService } from '../services/supabaseClient';
import { CREDIT_CSTS } from '../services/taxEngine';
import { fiscalMapping } from '../services/fiscalMapping';


export const Documents: React.FC<DocumentsProps> = ({ companyId, documents, onUploadSuccess, onAddLearning, user }) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importMessage, setImportMessage] = useState<{type: 'success' | 'error', text: string} | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [selectedDocument, setSelectedDocument] = useState<FiscalDocument | null>(null);
  const [activeTab, setActiveTab] = useState<'items' | 'audit'>('items');

  const [editingItem, setEditingItem] = useState<InvoiceItem | null>(null);
  const [correctionForm, setCorrectionForm] = useState({ cstPis: '', cstCofins: '', cfop: '', justification: '' });

  const getTagValue = (parent: Element | Document, tagName: string): number => {
    const elements = parent.getElementsByTagName(tagName);
    if (elements.length > 0) {
        return parseFloat(elements[0].textContent || "0");
    }
    return 0;
  };

  const getTagText = (parent: Element | Document, tagName: string): string => {
    const elements = parent.getElementsByTagName(tagName);
    return elements.length > 0 ? elements[0].textContent || "" : "";
  };

  const parseAndUploadXML = async (xmlText: string, fileName: string): Promise<boolean> => {
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlText, "text/xml");
    
    if (!xmlDoc.getElementsByTagName("nfeProc").length && !xmlDoc.getElementsByTagName("infNFe").length) {
        return false;
    }

    const accessKey = getTagText(xmlDoc, "chNFe");
    const dhEmi = getTagText(xmlDoc, "dhEmi");
    const vNF = getTagValue(xmlDoc, "vNF");
    const emitCNPJ = getTagText(xmlDoc, "CNPJ");
    const emitName = getTagText(xmlDoc, "xNome");
    
    const dets = xmlDoc.getElementsByTagName("det");
    const items: InvoiceItem[] = [];
    
    let docTotalICMS = 0;
    let docTotalPIS = 0;
    let docTotalCOFINS = 0;
    let docTotalIPI = 0;

    let operationType: 'entry' | 'exit' = 'entry'; 

    for (let i = 0; i < dets.length; i++) {
        const prod = dets[i].getElementsByTagName("prod")[0];
        const imposto = dets[i].getElementsByTagName("imposto")[0];
        
        if (prod) {
            const cfop = getTagText(prod, "CFOP");
            const amount = getTagValue(prod, "vProd");
            
            if (i === 0) {
                const firstDigit = cfop.charAt(0);
                if (['5', '6', '7'].includes(firstDigit)) {
                    operationType = 'exit';
                }
            }

            const vICMS = getTagValue(imposto, "vICMS");
            const pICMS = getTagValue(imposto, "pICMS"); 
            const vPIS = getTagValue(imposto, "vPIS");
            const pPIS = getTagValue(imposto, "pPIS"); 
            const vCOFINS = getTagValue(imposto, "vCOFINS");
            const pCOFINS = getTagValue(imposto, "pCOFINS"); 
            const vIPI = getTagValue(imposto, "vIPI");
            const pIPI = getTagValue(imposto, "pIPI"); 
            
            const cst = getTagText(imposto, "CST"); 
            const cstPis = getTagText(imposto.getElementsByTagName("PIS")[0] || imposto, "CST");
            const cstCofins = getTagText(imposto.getElementsByTagName("COFINS")[0] || imposto, "CST");

            docTotalICMS += vICMS;
            docTotalPIS += vPIS;
            docTotalCOFINS += vCOFINS;
            docTotalIPI += vIPI;

            items.push({
                name: getTagText(prod, "xProd"),
                ncm: getTagText(prod, "NCM"),
                cfop: cfop,
                cst: cst,
                cstPis: cstPis,
                cstCofins: cstCofins,
                amount: amount,
                vICMS,
                pICMS,
                vPIS,
                pPIS,
                vCOFINS,
                pCOFINS,
                vIPI,
                pIPI
            });
        }
    }

    // Prepare Object for Supabase
    const docToSave: FiscalDocument = {
      id: '', // Generated by DB
      company_id: companyId,
      name: fileName,
      type: 'NFe',
      operation_type: operationType,
      date: dhEmi.split('T')[0] || new Date().toISOString().split('T')[0],
      status: 'classified',
      confidence: 1.0,
      amount: vNF,
      items: items,
      xml_content: xmlText,
      access_key: accessKey,
      issuer_cnpj: emitCNPJ,
      issuer_name: emitName,
      total_icms: docTotalICMS,
      total_pis: docTotalPIS,
      total_cofins: docTotalCOFINS,
      total_ipi: docTotalIPI
    };

    // Upload to Supabase
    try {
      await documentService.create(docToSave);
      return true;
    } catch (e) {
      console.error("Duplicate or DB Error", e);
      return false;
    }
  };

  const readFileContent = (file: File): Promise<{name: string, content: string}> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (e) => resolve({ name: file.name, content: e.target?.result as string });
        reader.onerror = (e) => reject(e);
        reader.readAsText(file);
    });
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (!files || files.length === 0) return;

    setIsProcessing(true);
    setImportMessage(null);

    try {
        const filesData = await Promise.all(Array.from(files).map(readFileContent));
        let successCount = 0;

        // Process sequentially to avoid DB connection limits if many files
        for (const fileData of filesData) {
           if (fileData.name.toLowerCase().endsWith('.xml')) {
              const saved = await parseAndUploadXML(fileData.content, fileData.name);
              if (saved) successCount++;
           }
        }

        setImportMessage({
            type: successCount > 0 ? 'success' : 'error',
            text: `Processamento concluído: ${successCount} salvos no Banco de Dados.`
        });
        
        if (successCount > 0) {
          onUploadSuccess();
        }

    } catch (error) {
        console.error("Erro no upload em lote:", error);
        setImportMessage({
            type: 'error',
            text: "Erro crítico ao processar arquivos."
        });
    } finally {
        setIsProcessing(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };
  
  const handleOpenCorrection = (item: InvoiceItem) => {
    setEditingItem(item);
    setCorrectionForm({
      cstPis: item.cstPis || '',
      cstCofins: item.cstCofins || '',
      cfop: item.cfop || '',
      justification: ''
    });
  };

  const handleSaveCorrection = () => {
    if (!editingItem || !correctionForm.justification || !user) {
      alert("A justificativa é obrigatória para o aprendizado da IA.");
      return;
    }

    const learning: Omit<AILearning, 'id' | 'created_at'> = {
      company_id: companyId,
      user_id: user.id,
      learning_type: 'cst_correction', 
      context: {
        itemName: editingItem.name,
        itemNCM: editingItem.ncm,
      },
      corrected_value: {
        cstPis: correctionForm.cstPis,
        cstCofins: correctionForm.cstCofins,
        cfop: correctionForm.cfop,
      },
      justification: correctionForm.justification,
    };

    onAddLearning(learning);
    setEditingItem(null);
  };

  return (
    <div className="space-y-6 animate-fade-in relative">
      {isProcessing && (
        <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center rounded-xl">
             <Loader2 className="animate-spin text-indigo-600 mb-2" size={40} />
             <p className="text-slate-600 font-semibold">Enviando para Supabase...</p>
        </div>
      )}

      {/* --- HEADER ACTIONS --- */}
      <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
             <FileText className="text-indigo-600" /> Gestão de Documentos (DB)
          </h1>
          <p className="text-slate-500">Clique em um documento para auditar os itens e ensinar a IA.</p>
        </div>
        <div>
            <input 
                type="file" 
                accept=".xml" 
                multiple 
                ref={fileInputRef} 
                className="hidden" 
                onChange={handleFileUpload} 
            />
            <button 
                onClick={() => fileInputRef.current?.click()}
                disabled={isProcessing || user.role === 'employee'}
                className="bg-indigo-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-indigo-700 shadow-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed w-full md:w-auto"
                title={user.role === 'employee' ? 'Permissão insuficiente para upload' : 'Fazer upload de XMLs'}
            >
                <Upload size={18} /> Upload XML
            </button>
        </div>
      </div>

      {importMessage && (
          <div className={`p-4 rounded-lg flex items-center gap-2 ${importMessage.type === 'success' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' : 'bg-red-50 text-red-700'}`}>
              <CheckCircle size={18} />
              {importMessage.text}
          </div>
      )}

      {documents.length > 0 ? (
        <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden">
            <div className="overflow-x-auto custom-scrollbar">
                <table className="w-full min-w-[700px]">
                    <thead className="bg-slate-50 border-b border-slate-100">
                        <tr>
                            <th className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase">Operação</th>
                            <th className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase">Chave / Nome</th>
                            <th className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase">Data</th>
                            <th className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase">Valor Total</th>
                            <th className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase">Auditoria</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {documents.map((doc) => (
                            <tr 
                                key={doc.id} 
                                className="hover:bg-blue-50/50 transition-colors cursor-pointer group"
                                onClick={() => { setSelectedDocument(doc); setActiveTab('items'); }}
                            >
                                <td className="px-6 py-4">
                                    {doc.operation_type === 'exit' ? (
                                        <div className="flex items-center gap-1 text-emerald-600 bg-emerald-50 px-2 py-1 rounded-md w-fit text-xs font-bold">
                                            <ArrowLeft size={12} /> SAÍDA
                                        </div>
                                    ) : (
                                        <div className="flex items-center gap-1 text-blue-600 bg-blue-50 px-2 py-1 rounded-md w-fit text-xs font-bold">
                                            <ArrowRight size={12} /> ENTRADA
                                        </div>
                                    )}
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex flex-col">
                                        <span className="font-medium text-slate-700 truncate w-48" title={doc.name}>{doc.name}</span>
                                        <span className="text-[10px] text-slate-400 font-mono bg-slate-100 px-1 rounded w-fit">{doc.access_key?.substring(0, 24)}...</span>
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-sm text-slate-500">
                                    {new Date(doc.date).toLocaleDateString()}
                                </td>
                                <td className="px-6 py-4 text-sm font-bold text-slate-800">
                                    {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(doc.amount)}
                                </td>
                                <td className="px-6 py-4">
                                    <div className="text-xs text-blue-600 font-medium opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1">
                                        <Search size={14} /> Ver Detalhes
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
      ) : (
        <div className="text-center py-20 bg-white rounded-xl border border-slate-100 border-dashed">
            <FileText size={48} className="mx-auto text-slate-200 mb-4" />
            <h3 className="text-lg font-medium text-slate-500">Nenhum documento importado</h3>
            <p className="text-sm text-slate-400">Faça o upload dos XMLs para começar.</p>
        </div>
      )}

      {/* --- DRILL-DOWN MODAL --- */}
      {selectedDocument && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-[100] flex items-center justify-center p-4 animate-fade-in">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-5xl h-[90vh] flex flex-col overflow-hidden">
                {/* Modal Header */}
                <div className="bg-slate-900 text-white p-6 shrink-0">
                    <div className="flex justify-between items-start">
                        <div>
                            <div className="flex flex-wrap items-center gap-3 mb-2">
                                <h2 className="text-xl font-bold">Detalhamento do Documento</h2>
                                <span className={`px-2 py-0.5 rounded text-xs font-bold ${selectedDocument.operation_type === 'exit' ? 'bg-emerald-500 text-white' : 'bg-blue-500 text-white'}`}>
                                    {selectedDocument.operation_type === 'exit' ? 'NOTA DE SAÍDA' : 'NOTA DE ENTRADA'}
                                </span>
                            </div>
                            <p className="text-sm text-slate-400 font-mono break-all">{selectedDocument.access_key}</p>
                        </div>
                        <button onClick={() => setSelectedDocument(null)} className="text-slate-400 hover:text-white transition-colors">
                            <X size={24} />
                        </button>
                    </div>
                    {/* Tabs */}
                    <div className="mt-4 border-b border-slate-700">
                        <button onClick={() => setActiveTab('items')} className={`px-4 py-2 text-sm font-medium ${activeTab === 'items' ? 'text-white border-b-2 border-blue-500' : 'text-slate-400'}`}>Itens da Nota</button>
                        <button onClick={() => setActiveTab('audit')} className={`px-4 py-2 text-sm font-medium ${activeTab === 'audit' ? 'text-white border-b-2 border-blue-500' : 'text-slate-400'}`}>Histórico de Auditoria</button>
                    </div>
                </div>

                {/* Modal Content */}
                <div className="flex-1 overflow-y-auto p-4 md:p-6 bg-slate-50">
                    {activeTab === 'items' ? (
                        <div>
                            <h3 className="font-bold text-slate-800 mb-4">Itens da Nota Fiscal ({selectedDocument.items?.length || 0})</h3>
                            <div className="bg-white rounded-lg shadow-sm border border-slate-200 overflow-x-auto custom-scrollbar">
                                {/* Table for items... */}
                                 <table className="w-full text-sm min-w-[900px]">
                                    <thead className="bg-slate-100 border-b border-slate-200 text-xs font-semibold text-slate-600 uppercase">
                                        <tr>
                                            <th className="px-4 py-3 text-left">Produto / Serviço</th>
                                            <th className="px-4 py-3 text-left w-48">CFOP</th>
                                            <th className="px-4 py-3 text-center w-28">CST PIS/COF</th>
                                            <th className="px-4 py-3 text-right">Valor Item</th>
                                            <th className="px-4 py-3 text-right">PIS/COFINS</th>
                                            <th className="px-4 py-3 text-center">Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-100">
                                        {selectedDocument.items?.map((item, idx) => {
                                            const cst = item.cstPis || item.cstCofins || '99';
                                            const hasCredit = CREDIT_CSTS.includes(cst) && selectedDocument.operation_type === 'entry';
                                            
                                            return (
                                                <tr key={idx} className="hover:bg-slate-50">
                                                    <td className="px-4 py-3">
                                                        <p className="font-medium text-slate-800 truncate max-w-xs" title={item.name}>{item.name}</p>
                                                        <p className="text-xs text-slate-400">NCM: {item.ncm}</p>
                                                    </td>
                                                    <td className="px-4 py-3 text-xs text-slate-500">
                                                        <div className="flex items-center gap-2 group relative">
                                                            <span className="font-mono bg-slate-200 text-slate-600 px-2 py-0.5 rounded">{item.cfop}</span>
                                                            <BookOpen size={14} className="text-slate-400" />
                                                            <div className="absolute left-0 bottom-full mb-2 w-72 p-2 bg-slate-800 text-white text-xs rounded-lg shadow-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-10">
                                                                {fiscalMapping.getCFOPDescription(item.cfop)}
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td className="px-4 py-3 text-center">
                                                        <span className={`px-2 py-1 rounded text-xs font-bold border ${
                                                            hasCredit 
                                                            ? 'bg-emerald-100 text-emerald-700 border-emerald-200' 
                                                            : 'bg-slate-100 text-slate-500 border-slate-200'
                                                        }`}>
                                                            {cst}
                                                        </span>
                                                    </td>
                                                    <td className="px-4 py-3 text-right font-medium">
                                                        {item.amount.toLocaleString('pt-BR', {minimumFractionDigits: 2})}
                                                    </td>
                                                    <td className="px-4 py-3 text-right text-xs font-mono text-slate-600">
                                                        {(item.vPIS + item.vCOFINS).toFixed(2)}
                                                    </td>
                                                    <td className="px-4 py-3 text-center">
                                                        <button onClick={() => handleOpenCorrection(item)} disabled={user.role === 'employee'} className="text-xs text-indigo-600 hover:underline flex items-center gap-1 mx-auto disabled:opacity-50 disabled:cursor-not-allowed">
                                                            <Edit size={12} /> Corrigir
                                                        </button>
                                                    </td>
                                                </tr>
                                            );
                                        })}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    ) : (
                        <div>
                            <h3 className="font-bold text-slate-800 mb-4">Linha do Tempo de Alterações</h3>
                            {selectedDocument.history && selectedDocument.history.length > 0 ? (
                                <div className="space-y-4">
                                    {selectedDocument.history.map(entry => (
                                        <div key={entry.id} className="flex gap-4">
                                            <div className="flex flex-col items-center">
                                                <div className="w-8 h-8 rounded-full bg-slate-200 flex items-center justify-center ring-4 ring-slate-50">
                                                    <Clock size={16} className="text-slate-500" />
                                                </div>
                                                <div className="w-px h-full bg-slate-200"></div>
                                            </div>
                                            <div className="pb-4 w-full">
                                                <p className="text-xs text-slate-400">{new Date(entry.timestamp).toLocaleString()}</p>
                                                <p className="font-semibold text-slate-700">{entry.action} <span className="text-slate-500 font-normal">por {entry.user_name}</span></p>
                                                <p className="text-sm text-slate-600 mt-1">{entry.details}</p>
                                                {entry.reason && (
                                                    <p className="text-xs text-slate-500 mt-2 p-2 bg-slate-100 rounded border border-slate-200 italic">
                                                        <strong>Justificativa:</strong> {entry.reason}
                                                    </p>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <p className="text-slate-500 italic">Nenhuma alteração registrada para este documento.</p>
                            )}
                        </div>
                    )}
                </div>
            </div>
        </div>
      )}

      {/* --- CORRECTION MODAL --- */}
      {editingItem && (
        <div className="fixed inset-0 bg-black/70 z-[110] flex items-center justify-center p-4 animate-fade-in">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg">
            <div className="p-4 border-b flex justify-between items-center">
              <div>
                <h3 className="font-bold text-lg text-slate-800">Ensinar IA - Corrigir Classificação</h3>
                <p className="text-xs text-slate-500 truncate max-w-sm">Item: {editingItem.name}</p>
              </div>
              <button onClick={() => setEditingItem(null)} className="text-slate-400 hover:text-slate-600"><X size={20}/></button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                      <label className="text-xs font-medium text-slate-600">CST PIS</label>
                      <input type="text" value={correctionForm.cstPis} onChange={e => setCorrectionForm({...correctionForm, cstPis: e.target.value})} className="w-full p-2 mt-1 border border-slate-300 rounded-lg text-sm"/>
                  </div>
                   <div>
                      <label className="text-xs font-medium text-slate-600">CST COFINS</label>
                      <input type="text" value={correctionForm.cstCofins} onChange={e => setCorrectionForm({...correctionForm, cstCofins: e.target.value})} className="w-full p-2 mt-1 border border-slate-300 rounded-lg text-sm"/>
                  </div>
                   <div>
                      <label className="text-xs font-medium text-slate-600">CFOP</label>
                      <input type="text" value={correctionForm.cfop} onChange={e => setCorrectionForm({...correctionForm, cfop: e.target.value})} className="w-full p-2 mt-1 border border-slate-300 rounded-lg text-sm"/>
                  </div>
              </div>
              <div>
                  <label className="text-xs font-medium text-slate-600">Justificativa <span className="text-red-500">*</span></label>
                  <input type="text" placeholder="Ex: Este serviço é insumo essencial, gera crédito." value={correctionForm.justification} onChange={e => setCorrectionForm({...correctionForm, justification: e.target.value})} className="w-full p-2 mt-1 border border-slate-300 rounded-lg text-sm"/>
                  <p className="text-[10px] text-slate-400 mt-1">Esta justificativa será usada para treinar a IA para casos futuros nesta empresa.</p>
              </div>
              <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
                <button onClick={() => setEditingItem(null)} className="px-4 py-2 bg-slate-100 text-slate-700 rounded-lg text-sm font-medium hover:bg-slate-200">Cancelar</button>
                <button onClick={handleSaveCorrection} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">Salvar Aprendizado</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};